### ISSUE TITLE
Use MessageId instead of Transaction_id for Rosetta Transaction Identifier

### ISSUE THREAD

**Issue by rufsam** [iotaledger/rosetta-iota#45] opened 2021-03-22 13:35 UTC
A Rosetta Transaction (https://www.rosetta-api.org/docs/models/Transaction.html) contains the field `transaction_identifier`.
Currently we populate this field with the `bee_message::TransactionId`.

Would it be possible to populate the field with the `bee_message::MessageId`?
Or would this have any bad implications?

**Comment by samuel-rufi** [comment] 2021-11-29 13:41
Update: A disadvantage of using `MessageId` instead of `TransactionId` could be that if a constructed transaction (before it is confirmed) is replayed by an attacker, the message ID returned during construction/submit will not be the "confirmed message id".

**Comment by samuel-rufi** [comment] 2021-11-30 13:33
Since we can't return the `MessageId` for the above reason, I will close this issue.

**Closed by samuel-rufi** 2021-11-30 13:33 UTC
